### ISSUE TITLE
Smartypants interferes with Error 404 pages with latest update

### ISSUE THREAD

**Issue by a1studmuffin** [getgrav/grav-plugin-smartypants#3]
Heya! In Grav v1.1.1 with Smartypants v2.5.0 and Error v1.5.0 (fresh sandbox install):

Triggering a 404 error page results in a "Crikey!" error:

`Unexpected character "&" in "@Page:<my install folder>\user\plugins\error/pages" at line 1.`

The full string it's complaining about is:

`{{ &#8216;PLUGIN_ERROR.ERROR_MESSAGE&#8217;|t }}`

Smartypants seems to be messing with the pre-translated string "PLUGIN_ERROR.ERROR_MESSAGE", changing the double quotes into fancy quotes, which interferes with Twig's ability to translate the message. Full callstack:

Twig_Error_Syntax
…\vendor\twig\twig\lib\Twig\Lexer.php284
19 Twig_Lexer lexExpression
…\vendor\twig\twig\lib\Twig\Lexer.php216
18 Twig_Lexer lexVar
…\vendor\twig\twig\lib\Twig\Lexer.php115
17 Twig_Lexer tokenize
…\vendor\twig\twig\lib\Twig\Environment.php581
16 Twig_Environment tokenize
…\vendor\twig\twig\lib\Twig\Environment.php671
15 Twig_Environment compileSource
…\vendor\twig\twig\lib\Twig\Environment.php396
14 Twig_Environment loadTemplate
…\vendor\twig\twig\lib\Twig\Environment.php347
13 Twig_Environment render
…\system\src\Grav\Common\Twig\Twig.php242
12 Grav\Common\Twig\Twig processPage
…\system\src\Grav\Common\Page\Page.php702
11 Grav\Common\Page\Page processTwig
…\system\src\Grav\Common\Page\Page.php591
10 Grav\Common\Page\Page content
…\system\src\Grav\Common\Twig\Twig.php319
9 Grav\Common\Twig\Twig processSite
…\system\src\Grav\Common\Service\OutputServiceProvider.php19
8 Grav\Common\Service\OutputServiceProvider Grav\Common\Service{closure}
…\vendor\pimple\pimple\src\Pimple\Container.php113
7 Pimple\Container offsetGet
…\system\src\Grav\Common\Processors\RenderProcessor.php17
6 Grav\Common\Processors\RenderProcessor process
…\system\src\Grav\Common\Grav.php121
5 Grav\Common\Grav Grav\Common{closure}
…\system\src\Grav\Common\Grav.php383
4 Grav\Common\Grav Grav\Common{closure}
…\system\src\Grav\Common\Grav.php359
3 call_user_func_array
…\system\src\Grav\Common\Grav.php359
2 Grav\Common\Grav __call
…\system\src\Grav\Common\Grav.php122
1 Grav\Common\Grav measureTime
…\system\src\Grav\Common\Grav.php122
0 Grav\Common\Grav process
…\index.php45 

Cheers :)

**Comment by flaviocopes** [comment]
Interesting. I got this `Unexpected character "&"` error 3 times today in other issues, can't find the reason, I'm asking for `user` folders to replicate, but I haven't got one yet.

Care to PM me your `user/` folder (remove sensitive accounts and data folders) to gitter.im/flaviocopes?

**Comment by a1studmuffin** [comment]
This is really easy to repro on a clean install, just install Grav + Admin plugin v1.1.1 from here:

https://github.com/getgrav/grav/releases/download/1.1.1/grav-admin-v1.1.1.zip

Create a default user, add the Smartpants plugin, then browse to a non-existent URL like http://<yourgravsite>/blahblahblah

Happy to provide my user folder if you need it but it's probably easier to just repro via the above steps in a new sandbox.

**Comment by flaviocopes** [comment]
Oh I got it now! Could not get with my testing install - no worries then, thanks!

**Comment by flaviocopes** [comment]
Right, latest Errors has twig processing into the page to translate the error message.

Easily fixed by putting

```
smartypants:
    process_content: false
```

on top of `user/plugins/error/pages/error.md` but don't like this plugin interference / plugin-specific config into another.

@rhukster do you think it's the only way of Smartypants can hook in later? Looks like it's hooking into `onPageContentProcessed` so Twig processing in the page should already be fired?

**Comment by flaviocopes** [comment]
Ok was a conflict between Error and Smartypants plugins.

Released https://github.com/getgrav/grav-plugin-error/releases/tag/1.5.1, available soon in the GPM, should be fixed!

**Comment by a1studmuffin** [comment]
Brilliant! Thanks for the quick fix, much appreciated!
